package com.example.grantappforitacademy.responsemodel

import com.google.gson.annotations.SerializedName

data class Definitions(
//    @SerializedName("User") var User: User? = User(),
//    @SerializedName("BlogComment") var BlogComment: BlogComment? = BlogComment(),
//    @SerializedName("BlogPost") var BlogPost: BlogPost? = BlogPost(),
//    @SerializedName("BusinessAdvertComment") var BusinessAdvertComment: BusinessAdvertComment? = BusinessAdvertComment(),
//    @SerializedName("BusinessAdvert") var BusinessAdvert: BusinessAdvert? = BusinessAdvert(),
//    @SerializedName("AdvertCategory") var AdvertCategory: AdvertCategory? = AdvertCategory(),
//    @SerializedName("ChangePassword") var ChangePassword: ChangePassword? = ChangePassword(),
//    @SerializedName("EventComment") var EventComment: EventComment? = EventComment(),
    var Event: List<Event> = arrayListOf(),
//    @SerializedName("FacebookSocialAuth") var FacebookSocialAuth: FacebookSocialAuth? = FacebookSocialAuth(),
//    @SerializedName("GoogleSocialAuth") var GoogleSocialAuth: GoogleSocialAuth? = GoogleSocialAuth(),
//    @SerializedName("GrantComment") var GrantComment: GrantComment? = GrantComment(),
//    @SerializedName("Grant") var Grant: Grant? = Grant(),
//    @SerializedName("InvestComment") var InvestComment: InvestComment? = InvestComment(),
//    @SerializedName("Investment") var Investment: Investment? = Investment(),
//    @SerializedName("Knowledge") var Knowledge: Knowledge? = Knowledge(),
//    @SerializedName("TelegramLinks") var TelegramLinks: TelegramLinks? = TelegramLinks(),
//    @SerializedName("MyTokenObtainPair") var MyTokenObtainPair: MyTokenObtainPair? = MyTokenObtainPair(),
//    @SerializedName("TokenRefresh") var TokenRefresh: TokenRefresh? = TokenRefresh(),
//    @SerializedName("Method") var Method: Method? = Method(),
//    @SerializedName("Contacts") var Contacts: Contacts? = Contacts(),
//    @SerializedName("Email") var Email: Email? = Email(),
//    @SerializedName("PasswordToken") var PasswordToken: PasswordToken? = PasswordToken(),
//    @SerializedName("ResetToken") var ResetToken: ResetToken? = ResetToken(),
//    @SerializedName("UserPoll") var UserPoll: UserPoll? = UserPoll(),
//    @SerializedName("ResultPoll") var ResultPoll: ResultPoll? = ResultPoll(),
//    @SerializedName("ProviderAdvertComment") var ProviderAdvertComment: ProviderAdvertComment? = ProviderAdvertComment(),
//    @SerializedName("ProviderAdvert") var ProviderAdvert: ProviderAdvert? = ProviderAdvert(),
//    @SerializedName("QuestionsAndAnswers") var QuestionsAndAnswers: QuestionsAndAnswers? = QuestionsAndAnswers(),
//    @SerializedName("Sector") var Sector: Sector? = Sector(),
//    @SerializedName("Skill") var Skill: Skill? = Skill(),
//    @SerializedName("UserBusinessProfile") var UserBusinessProfile: UserBusinessProfile? = UserBusinessProfile(),
//    @SerializedName("UpdateUser") var UpdateUser: UpdateUser? = UpdateUser(),
//    @SerializedName("UserProviderProfile") var UserProviderProfile: UserProviderProfile? = UserProviderProfile(),
//    @SerializedName("WriteUs") var WriteUs: WriteUs? = WriteUs(),

)
